algoritmo "maior de idade"
// Função : Indicar se o usuario e maior ou menor de idade
// Autor : Aline Dantas
// Data : 18/05/2023
// Seção de Declarações 
var
idade:real
nome:caractere
inicio
escreval("Qual o seu nome?")
leia(nome)
escreval("Qual a sua idade?")
leia(idade)

se(idade<18)entao
  escreval(nome," você é de menor")
senao
  escreval(nome," você é de maior")
fimse
fimalgoritmo
