algoritmo "intervalo"
// Função : Mostrar se um número está entre o intervalo de 100 e 200
// Autor : Aline Dantas
// Data : 25/05/2023
// Seção de Declarações 
var
num: real
inicio
escreval("Digite o número: ")
leia(num)

se((num>99.99) e (num<200.01))entao
   escreval ("Ele está entre o intervalo de 100 e 200 :D")
senao
   escreval ("Ele não está entre 100 e 200 :(")
fimse
fimalgoritmo
