algoritmo "fahrenheit"
// Função : Converter os graus celsius para fahrenheit
// Autor : Aline
// Data : 09/03/2023
// Seção de Declarações 
var
celsius,fahren:real

inicio
//entrada

escreval("Quantos graus esta:")
leia(celsius)

//processamento
fahren <- (9*celsius+160)/5
//saida
escreval("--------------RESULTADO---------------")
escreval("A conversao fica: ",fahren)

fimalgoritmo
